export const countryNames: Record<string, string> = {
    "TR": "Turkey",
    "US": "United States",
    "GB": "United Kingdom",
    "DE": "Germany",
    "JP": "Japan",
    "CN": "China",
    "BR": "Brazil",
    "AU": "Australia",
    "CA": "Canada",
    "EG": "Egypt",
    "FR": "France",
    "IN": "India",
    "ID": "Indonesia",
    "MX": "Mexico",
    "NG": "Nigeria",
    "PK": "Pakistan",
    "PH": "Philippines",
    "RU": "Russia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "PT": "Portugal",
    "ES": "Spain",
    "IT": "Italy"
};
