@Routiq.Api_HostAddress = http://localhost:5107

GET {{Routiq.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
###
POST {{Routiq.Api_HostAddress}}/api/routes/generate
Content-Type: application/json

{
  "passportCountry": "Turkey",
  "totalBudget": 1000,
  "durationDays": 7
}
