using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Routiq.Api.Entities;

/// <summary>
/// The primary reason a destination was filtered out during route generation.
/// This powers the "why NOT here" UI — the core V2 value proposition.
/// </summary>
public enum EliminationReason
{
    VisaRequired,        // Hard visa needed and user hasn't declared an approved one
    BudgetInsufficient,  // Daily cost tier × recommended days exceeds remaining budget
    DaysInsufficient,    // Not enough days left in the trip to meet minimum stay
    BannedDestination,   // Diplomatic ban or known safety exclusion
    RegionMismatch       // Destination is outside the user's preferred region
}

/// <summary>
/// Audit log of one destination eliminated during a specific RouteQuery run.
/// Created by the route engine for every city that was considered but rejected.
/// Surfaced in the UI as a transparent explanation.
/// </summary>
public class RouteElimination
{
    public int Id { get; set; }

    public Guid RouteQueryId { get; set; }
    [ForeignKey(nameof(RouteQueryId))]
    public RouteQuery? RouteQuery { get; set; }

    public int DestinationId { get; set; }
    [ForeignKey(nameof(DestinationId))]
    public Destination? Destination { get; set; }

    public EliminationReason Reason { get; set; }

    /// <summary>
    /// Full human-readable explanation generated by the engine.
    /// E.g. "Bangkok eliminated: TR passport requires visa (avg 15 days processing). 
    ///        You declared no Thailand visa."
    /// </summary>
    [Required, MaxLength(600)]
    public string ExplanationText { get; set; } = string.Empty;
}
